/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GpaCalculatorRouteImport } from './routes/gpa-calculator'
import { Route as DegreePlannerRouteImport } from './routes/degree-planner'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as IndexRouteImport } from './routes/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GpaCalculatorRoute = GpaCalculatorRouteImport.update({
  id: '/gpa-calculator',
  path: '/gpa-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DegreePlannerRoute = DegreePlannerRouteImport.update({
  id: '/degree-planner',
  path: '/degree-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/dashboard': typeof DashboardRoute
  '/degree-planner': typeof DegreePlannerRoute
  '/gpa-calculator': typeof GpaCalculatorRoute
  '/login': typeof LoginRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/dashboard': typeof DashboardRoute
  '/degree-planner': typeof DegreePlannerRoute
  '/gpa-calculator': typeof GpaCalculatorRoute
  '/login': typeof LoginRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/dashboard': typeof DashboardRoute
  '/degree-planner': typeof DegreePlannerRoute
  '/gpa-calculator': typeof GpaCalculatorRoute
  '/login': typeof LoginRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/advisor' | '/dashboard' | '/degree-planner' | '/gpa-calculator' | '/login' | '/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advisor' | '/dashboard' | '/degree-planner' | '/gpa-calculator' | '/login' | '/roadmap'
  id: '__root__' | '/' | '/advisor' | '/dashboard' | '/degree-planner' | '/gpa-calculator' | '/login' | '/roadmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  DashboardRoute: typeof DashboardRoute
  DegreePlannerRoute: typeof DegreePlannerRoute
  GpaCalculatorRoute: typeof GpaCalculatorRoute
  LoginRoute: typeof LoginRoute
  RoadmapRoute: typeof RoadmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpa-calculator': {
      id: '/gpa-calculator'
      path: '/gpa-calculator'
      fullPath: '/gpa-calculator'
      preLoaderRoute: typeof GpaCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/degree-planner': {
      id: '/degree-planner'
      path: '/degree-planner'
      fullPath: '/degree-planner'
      preLoaderRoute: typeof DegreePlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  DashboardRoute: DashboardRoute,
  DegreePlannerRoute: DegreePlannerRoute,
  GpaCalculatorRoute: GpaCalculatorRoute,
  LoginRoute: LoginRoute,
  RoadmapRoute: RoadmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
