/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GpaCalculatorRouteImport } from './routes/gpa-calculator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as LoginAdminRouteImport } from './routes/login/admin'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GpaCalculatorRoute = GpaCalculatorRouteImport.update({
  id: '/gpa-calculator',
  path: '/gpa-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LoginRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRoute
  '/appointments': typeof AppointmentsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/gpa-calculator': typeof GpaCalculatorRoute
  '/login': typeof LoginRouteWithChildren
  '/messages': typeof MessagesRoute
  '/planning': typeof PlanningRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/admin': typeof LoginAdminRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRoute
  '/appointments': typeof AppointmentsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/gpa-calculator': typeof GpaCalculatorRoute
  '/login': typeof LoginRouteWithChildren
  '/messages': typeof MessagesRoute
  '/planning': typeof PlanningRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/admin': typeof LoginAdminRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRoute
  '/appointments': typeof AppointmentsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/gpa-calculator': typeof GpaCalculatorRoute
  '/login': typeof LoginRouteWithChildren
  '/messages': typeof MessagesRoute
  '/planning': typeof PlanningRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/admin': typeof LoginAdminRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/advisor'
    | '/appointments'
    | '/audit'
    | '/dashboard'
    | '/gpa-calculator'
    | '/login'
    | '/messages'
    | '/planning'
    | '/report'
    | '/settings'
    | '/auth/callback'
    | '/login/admin'
    | '/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/advisor'
    | '/appointments'
    | '/audit'
    | '/dashboard'
    | '/gpa-calculator'
    | '/login'
    | '/messages'
    | '/planning'
    | '/report'
    | '/settings'
    | '/auth/callback'
    | '/login/admin'
    | '/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/advisor'
    | '/appointments'
    | '/audit'
    | '/dashboard'
    | '/gpa-calculator'
    | '/login'
    | '/messages'
    | '/planning'
    | '/report'
    | '/settings'
    | '/auth/callback'
    | '/login/admin'
    | '/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdvisorRoute: typeof AdvisorRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuditRoute: typeof AuditRoute
  DashboardRoute: typeof DashboardRoute
  GpaCalculatorRoute: typeof GpaCalculatorRoute
  LoginRoute: typeof LoginRouteWithChildren
  MessagesRoute: typeof MessagesRoute
  PlanningRoute: typeof PlanningRoute
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpa-calculator': {
      id: '/gpa-calculator'
      path: '/gpa-calculator'
      fullPath: '/gpa-calculator'
      preLoaderRoute: typeof GpaCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof LoginRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoginRouteChildren {
  LoginAdminRoute: typeof LoginAdminRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginAdminRoute: LoginAdminRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdvisorRoute: AdvisorRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuditRoute: AuditRoute,
  DashboardRoute: DashboardRoute,
  GpaCalculatorRoute: GpaCalculatorRoute,
  LoginRoute: LoginRouteWithChildren,
  MessagesRoute: MessagesRoute,
  PlanningRoute: PlanningRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  StudentsStudentIdRoute: StudentsStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
